apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-2
  labels:
    app: example-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-2
  template:
    metadata:
      labels:
        app: example-2
    spec:
      containers:
      - name: example-2
        image: example-2:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: example-config
        env:
        - name: DEBUG
          value: {{ .Values.debug.example2 | quote }}
        - name: SCYLLA_KEYSPACE
          value: {{ .Values.scylla.keyspace.example | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: example-2
  labels:
    app: example-2
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: example-2
