apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  labels:
    app: example-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example-1.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: example-1
            port:
              number: 8080

