apiVersion: v2
name: example-apps
description: A Helm chart for Kubernetes deployments of example applications
type: application
version: 0.1.0
appVersion: "1.0"

maintainers:
  - name: Example
    email: your.email@example.com
